### ISSUE TITLE
运行过程中的一些报错

### ISSUE THREAD

**Issue by ent-crawl** [Lucareful/JingDongSpider#1]

**Comment by ent-crawl** [comment]
1.中间件里的：request.headers['user-agent'] = 'JD4iPhone/164880(iPhon ..  应该是headers;
2.另外settings的ROBOTSTXT_OBEY修改，
3.item里的规格和颜色对应的值反了：
 'product_option': {'规格型号': ['蓝色', '白色'],
                    '颜色': ['长宽高：143*97*52mm',
                           '长宽高：198*150*64mm'...

**Comment by ent-crawl** [comment]
[scrapy.core.scraper] ERROR: Spider error processing <GET https://cd.jd.com/promotion/v2?skuId=7674638&area=1_72_4137_0&c
at=14065,14076,14078> (referer: https://cdnware.m.jd.com/c1/skuDetail/apple/7.3.0/7674638.json)
Traceback (most recent call last):
  File "D:\ProgramData\Anaconda3\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "D:\ProgramData\Anaconda3\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "D:\ProgramData\Anaconda3\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 339, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "D:\ProgramData\Anaconda3\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "D:\ProgramData\Anaconda3\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "D:\hzl\Myproject\byx\JingDongSpider\jingDong\spiders\jd_product.py", line 133, in parse_product_ad
    result = json.loads(response.body.decode('GBK'))
UnicodeDecodeError: 'gbk' codec can't decode byte 0x80 in position 73: illegal multibyte sequence

这个异常怎么处理

**Comment by Lucareful** [comment]
> 1.中间件里的：request.headers['user-agent'] = 'JD4iPhone/164880(iPhon .. 应该是headers;
> 2.另外settings的ROBOTSTXT_OBEY修改，
> 3.item里的规格和颜色对应的值反了：
> 'product_option': {'规格型号': ['蓝色', '白色'],
> '颜色': ['长宽高：143_97_52mm',
> '长宽高：198_150_64mm'...

抱歉，不是很能理解你想表达的内容。我的item里没有什么颜色的值。如果方便请提供更详细的讲解。

**Comment by Lucareful** [comment]
> [scrapy.core.scraper] ERROR: Spider error processing <GET https://cd.jd.com/promotion/v2?skuId=7674638&area=1_72_4137_0&c
> at=14065,14076,14078> (referer: https://cdnware.m.jd.com/c1/skuDetail/apple/7.3.0/7674638.json)
> Traceback (most recent call last):
> File "D:\ProgramData\Anaconda3\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
> yield next(it)
> File "D:\ProgramData\Anaconda3\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
> for x in result:
> File "D:\ProgramData\Anaconda3\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 339, in
> return (_set_referer(r) for r in result or ())
> File "D:\ProgramData\Anaconda3\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in
> return (r for r in result or () if _filter(r))
> File "D:\ProgramData\Anaconda3\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in
> return (r for r in result or () if _filter(r))
> File "D:\hzl\Myproject\byx\JingDongSpider\jingDong\spiders\jd_product.py", line 133, in parse_product_ad
> result = json.loads(response.body.decode('GBK'))
> UnicodeDecodeError: 'gbk' codec can't decode byte 0x80 in position 73: illegal multibyte sequence
> 
> 这个异常怎么处理

应该是京东的数据接口变了，没有获取到值。暂时没时间去维护接口，见谅。

**Comment by ent-crawl** [comment]
> > 1.中间件里的：request.headers['user-agent'] = 'JD4iPhone/164880(iPhon .. 应该是headers;
> > 2.另外settings的ROBOTSTXT_OBEY修改，
> > 3.item里的规格和颜色对应的值反了：
> > 'product_option': {'规格型号': ['蓝色', '白色'],
> > '颜色': ['长宽高：143_97_52mm',
> > '长宽高：198_150_64mm'...
> 
> 抱歉，不是很能理解你想表达的内容。我的item里没有什么颜色的值。如果方便请提供更详细的讲解。
这个item我去看了下，是原网页的问题....
